version: '3'
services:
  restful_server: 
    image: restful-server
    build: 
      context: ./restful_server
      dockerfile: Dockerfile
    environment: 
      NODE_ENV: development
    ports:
      - 3002:3002
    volumes:
      - ./restful_server:/home/app/restful_server
      - /home/app/restful_server/node_modules
    depends_on:
      - "database_server"
  database_server: 
    image: database-server
    build: 
      context: ./database_server
      dockerfile: Dockerfile
    environment: 
      NODE_ENV: development
    ports:
      - 3001:3001
    volumes:
      - ./database_server:/home/app/database_server
      - /home/app/database_server/node_modules
    depends_on:
      - "mongo"
  amqp_server: 
    image: amqp-server
    build: 
      context: ./amqp_server
      dockerfile: Dockerfile
    environment: 
      NODE_ENV: development
    ports:
      - 3003:3003
    volumes:
      - ./amqp_server:/home/app/amqp_server
      - /home/app/amqp_server/node_modules
    depends_on:
      - "rabbitmq"
  consumer_server: 
    image: consumer-server
    build: 
      context: ./consumer_server
      dockerfile: Dockerfile
    environment: 
      NODE_ENV: development
    ports:
      - 3004:3003
    volumes:
      - ./consumer_server:/home/app/consumer_server
      - /home/app/consumer_server/node_modules
    depends_on:
      - "rabbitmq"
      - "amqp_server"
      - "database_server"
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo: 
    image: "mongo"
    ports: 
      - 27017:27017
